const details = {
	name: {
		first: "Abhiram",
		last: "Bylahalli Jagadish",
		nickname: "Abhi",
	},
	education: [
		{
			school: "Illinois Institute of Technology",
			url: "https://www.iit.edu",
			location: "Chicago, IL, USA",
			degree: "Masters",
			major: "Information Technology and Management",
			start: "Aug 2023",
			end: "May 2025",
			gpa: 3.8,
		},
		{
			school: "Visvesvaraya Technological University",
			url: "https://vtu.ac.in",
			location: "Belgaum, India",
			degree: "Bachelors",
			major: "Computer Science & Engineering",
			start: "Aug 2017",
			end: "Jul 2021",
			gpa: 3.4,
		},
	],
	experience: [
		{
			company: "Agilant Solutions Inc.",
			url: "https://www.goagilant.com",
			location: "Lisle, IL, USA",
			contract: "Internship",
			position: "Full Stack Developer Intern",
			start: "Jul 2024",
			end: "Sep 2024",
			description: [
				"Collaborated with UI/UX teams to design versatile ReactJS components, improving feature deployment speed by 10%.",
				"Streamlined backend services by optimizing Spring Boot database queries, reducing response times by 30%.",
				"Implemented OAuth 2.0 and JWT for secure authentication, improving customer satisfaction by 12%.",
			],
			skills: ["ReactJS", "Spring Boot", "OAuth 2.0", "JWT"],
		},
		{
			company: "Accenture",
			url: "https://www.accenture.com",
			location: "Bangalore, India",
			contract: "Full-time",
			position: "Software Developer",
			start: "Oct 2021",
			end: "Jul 2023",
			description: [
				"Integrated Redis caching to handle growing database loads, reducing latency by 25%.",
				"Developed scalable REST APIs for microservices migration, improving platform scalability by 20%.",
				"Deployed Kubernetes clusters to ensure zero downtime during production rollouts.",
			],
			skills: ["Spring Boot", "Redis", "Kubernetes", "REST APIs"],
		},
		{
			company: "SMMUD",
			location: "Bangalore, India",
			contract: "Full-time",
			position: "Full Stack Developer",
			start: "Jun 2021",
			end: "Oct 2021",
			description: [
				"Developed customer-facing modules using Next.js and FastAPI, reducing operational inefficiencies by 20%.",
				"Optimized GraphQL APIs, decreasing payload sizes by 40% and cutting hosting costs by 15%.",
				"Implemented Progressive Web App features, increasing user engagement by 20%.",
			],
			skills: ["Next.js", "FastAPI", "GraphQL", "PWA"],
		},
	],
	projects: [
		{
			name: "Expense Tracker",
			description: [
				"Built a financial management tool with FastAPI, React, Zustand, and MongoDB.",
				"Implemented secure authentication with JWT and Argon2.",
				"Deployed the solution on AWS using Docker and CI/CD pipelines, boosting user retention by 20%.",
			],
			skills: ["FastAPI", "React", "MongoDB", "AWS"],
		},
		{
			name: "TogaCommerce",
			description: [
				"Architected a scalable e-commerce platform using Spring Boot and React.",
				"Leveraged Docker and load balancing to handle peak traffic efficiently.",
				"Improved sales completion rate by 15% with a responsive UI.",
			],
			skills: ["Spring Boot", "React", "Docker"],
		},
	],
	skills: {
		cloud: [
			"AWS (Lambda, EC2, Elastic Beanstalk, S3, CloudFormation)",
			"Docker",
			"Kubernetes",
			"Terraform",
			"Jenkins (CI/CD)",
		],
		languages: ["JavaScript", "TypeScript", "Java", "Python"],
		frontend: [
			"ReactJS (Redux, Zustand)",
			"React Hooks",
			"Tailwind CSS",
			"Storybook",
			"HTML",
			"CSS",
			"SCSS",
			"Bootstrap",
		],
		backend: [
			"Spring Boot",
			"Node.js",
			"REST APIs",
			"Spring Data JPA",
			"Hibernate",
			"FastAPI",
			"GraphQL",
			"Microservices",
		],
		databases: ["MongoDB", "MySQL", "PostgreSQL", "Redis"],
		security: ["OAuth 2.0", "JWT", "OpenID Connect", "Argon2", "SSL/TLS"],
		tools: ["Postman", "Jira", "Git", "Cypress", "Prometheus"],
	},
	certifications: [
		{
			title: "AWS Certified Solutions Architect Associate",
			status: "Expected November 2024",
		},
	],
	contact: {
		address: "USA",
		email: "abhiram.bj@gmail.com",
		phone: "+1 (312) 877-8160",
		website: "https://abhirambj.github.io/portfolio",
		linkedin: "https://linkedin.com/in/abhirambj",
		github: "https://github.com/abhirambj",
	},
};

export default details;
